# Generated by Django 4.2.6 on 2023-11-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_alter_event_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name="event",
            name="endTime",
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="startTime",
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
