# Generated by Django 4.2.6 on 2023-11-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=2000)),
                ("startTime", models.DateTimeField()),
                ("endTime", models.DateTimeField()),
            ],
        ),
    ]
