# Generated by Django 4.2.6 on 2023-11-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_alter_event_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name="event",
            name="endTime",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="event",
            name="startTime",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
